/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.elster.nppTraceMonitor;

import com.elster.nppTraceMonitor.utils.SystemUtils;
import java.io.*;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author lu1721
 */
public class PathDialog extends javax.swing.JDialog {

    
    // Simple Console Logger
    private static final Logger LOGGER = Logger.getLogger(ColorDialog.class.getName());
    
    /** Creates new form PathDialog */
    public PathDialog (java.awt.Frame parent, boolean modal) {
        super (parent, modal);
        initComponents ();
        
        // load preferences
        Properties properties = new Properties();
        try {
            InputStream in = new FileInputStream (new File(SystemUtils.defaultPropertiesDirectory (), "paths.properties") );
            properties.load(in);
            traceFilesEdt.setText( properties.getProperty ("traceFilesDir", "Y:\\SDCard\\Traces") );
            editorEdt.setText( properties.getProperty ("editor", "") );
            return;
        } catch(FileNotFoundException e ) {
            LOGGER.log(Level.INFO, "Properties were not written before. Assigning standard values");
        } catch(IOException e) { 
            System.out.println("IOException while reading tracecolors.properties");
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings ("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        traceFilesEdt = new javax.swing.JTextField();
        traceFilesBtn = new javax.swing.JButton();
        traceFilesLbl = new javax.swing.JLabel();
        editorLbl = new javax.swing.JLabel();
        editorBtn = new javax.swing.JButton();
        editorEdt = new javax.swing.JTextField();
        okBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        traceFilesEdt.setEditable(false);
        traceFilesEdt.setText("Y:\\SDCard\\Traces");
        traceFilesEdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traceFilesEdtActionPerformed(evt);
            }
        });

        traceFilesBtn.setText("Change...");
        traceFilesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traceFilesBtnActionPerformed(evt);
            }
        });

        traceFilesLbl.setText("Trace Files Directory:");

        editorLbl.setText("Editor:");

        editorBtn.setText("Change...");
        editorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editorBtnActionPerformed(evt);
            }
        });

        editorEdt.setEditable(false);

        okBtn.setText("Ok");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(traceFilesLbl)
                            .addComponent(editorLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(traceFilesEdt, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                            .addComponent(editorEdt))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editorBtn)
                    .addComponent(traceFilesBtn))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(traceFilesEdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(traceFilesBtn)
                    .addComponent(traceFilesLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editorLbl)
                    .addComponent(editorBtn)
                    .addComponent(editorEdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okBtn)
                    .addComponent(cancelBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void traceFilesEdtActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traceFilesEdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_traceFilesEdtActionPerformed

    private void traceFilesBtnActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traceFilesBtnActionPerformed
        // Select new trace files directory
        JFileChooser chooser = new JFileChooser( traceFilesEdt.getText () );
        chooser.setFileSelectionMode (JFileChooser.DIRECTORIES_ONLY);

        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            // Update searchpath and set trace file to selected file
            traceFilesEdt.setText ( chooser.getSelectedFile().toString() );
        }
    }//GEN-LAST:event_traceFilesBtnActionPerformed

    private void editorBtnActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editorBtnActionPerformed
        // Select new editor filepath
        JFileChooser chooser = new JFileChooser( editorEdt.getText () );
        chooser.setFileFilter(new javax.swing.filechooser.FileFilter() {

            @Override
            public boolean accept(File f) {
                return true;
            }

            @Override
            public String getDescription() {
                return "Your favourite Editor";
            }
        });
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            editorEdt.setText( chooser.getSelectedFile().toString () );
        }
    }//GEN-LAST:event_editorBtnActionPerformed

    private void cancelBtnActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void okBtnActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        try  {
            Properties prop = new Properties();            
            OutputStream out = new FileOutputStream (new File(SystemUtils.defaultPropertiesDirectory (), "paths.properties") );
            prop.setProperty ("traceFilesDir", traceFilesEdt.getText() );
            prop.setProperty ("editor", editorEdt.getText ());
            prop.store(out, "path properties");
        }        
        catch( IOException e ) {
            System.out.println("IOException");
        }
        catch( Exception e ) {
            JOptionPane.showMessageDialog (this, e, "Exception", JOptionPane.ERROR_MESSAGE);
        }
            
        if( this.getParent () instanceof TraceMonitorFrame )
            ((TraceMonitorFrame)this.getParent ()).loadPaths();
        this.dispose ();
    }//GEN-LAST:event_okBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main (String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels ())
            {
                if ("Nimbus".equals (info.getName ()))
                {
                    javax.swing.UIManager.setLookAndFeel (info.getClassName ());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger (PathDialog.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger (PathDialog.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger (PathDialog.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger (PathDialog.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater (new Runnable () {

            public void run () {
                PathDialog dialog = new PathDialog (new javax.swing.JFrame (), true);
                dialog.addWindowListener (new java.awt.event.WindowAdapter () {

                    @Override
                    public void windowClosing (java.awt.event.WindowEvent e) {
                        System.exit (0);
                    }
                });
                dialog.setVisible (true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton editorBtn;
    private javax.swing.JTextField editorEdt;
    private javax.swing.JLabel editorLbl;
    private javax.swing.JButton okBtn;
    private javax.swing.JButton traceFilesBtn;
    private javax.swing.JTextField traceFilesEdt;
    private javax.swing.JLabel traceFilesLbl;
    // End of variables declaration//GEN-END:variables
}
